运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。

In [15]:
import torch

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [17]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

在X和Y相同位置的元素，判断给出的逻辑语句是否为真

用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

In [21]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

换成三维张量：

In [22]:
a = torch.arange(6).reshape((3,1,2))
b = torch.arange(4).reshape((1,2,2))

print(a)
print(b)
print(a + b)

tensor([[[0, 1]],

        [[2, 3]],

        [[4, 5]]])
tensor([[[0, 1],
         [2, 3]]])
tensor([[[0, 2],
         [2, 4]],

        [[2, 4],
         [4, 6]],

        [[4, 6],
         [6, 8]]])
