1. 本节中定义了形状$(2,3,4)$的张量`X`。`len(X)`的输出结果是什么？
1. 对于任意形状的张量`X`,`len(X)`是否总是对应于`X`特定轴的长度?这个轴是什么?
1. 运行`A/A.sum(axis=1)`，看看会发生什么。请分析一下原因？
1. 考虑一个具有形状$(2,3,4)$的张量，在轴0、1、2上的求和输出是什么形状?
1. 为`linalg.norm`函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?

In [5]:
import torch
X = torch.arange(24).reshape(2, 3, 4)
len(X)

2

len(X)返回的是张量最外层的长度，也就是第0轴的大小。对于任意张量X，len(X)总是等于第0轴的长度

In [6]:
A = torch.arange(20).reshape(5, 4)
A / A.sum(axis=1)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

A的形状是（5，4），求和的形状是（5，），不能进行广播，直接相除会报错，改正：

In [7]:
A / A.sum(axis=1, keepdims=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [9]:
A.shape

torch.Size([5, 4])

In [10]:
A.sum(axis=1, keepdims=True).shape

torch.Size([5, 1])

此时的形状可以进行广播为（5，4），能进行逐元素相除

In [13]:
X.sum(axis=0)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [14]:
X.sum(axis=1)

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [15]:
X.sum(axis=2)

tensor([[ 6, 22, 38],
        [54, 70, 86]])

没有特别指定dim，那么torch.linalg.norm(X)会把整个张量看成一个“大向量”，然后计算它的范数。
对于多维张量，这等价于把所有元素平方后求和，再开根号。，最后输出一个标量

In [17]:
X = torch.arange(24, dtype=torch.float32).reshape(2,3,4)
torch.linalg.norm(X)

tensor(65.7571)